'use client';
import { FormEvent,useState } from 'react';
import type { FounderInvestorDiscoveryCandidate } from '@/lib/founder/investor-discovery-core';
import { recordFounderInvestorResearchCandidate } from './investor-actions';
export function FounderInvestorDiscoveryPanel(){const [query,setQuery]=useState('AI SaaS and business software investors relevant to GCC/MENA expansion'),[candidates,setCandidates]=useState<FounderInvestorDiscoveryCandidate[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy||!query.trim())return;setBusy(true);setError('');try{const response=await fetch('/api/founder/investor-discovery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})}),payload=await response.json() as {candidates?:FounderInvestorDiscoveryCandidate[];error?:string};if(!response.ok||!payload.candidates)throw new Error(payload.error||'Investor discovery unavailable');setCandidates(payload.candidates);}catch(cause){setError(cause instanceof Error?cause.message:'Investor discovery unavailable');}finally{setBusy(false);}}
 return <section className="panel"><div className="headerRow"><div><h2>Investor discovery</h2><p className="muted">Live sourced discovery only. Results are not investor interest or recommendations. Saving creates DISCOVERED_EXTERNAL research, never CRM confirmation.</p></div><span className="status">LIVE WEB · OWNER REVIEW</span></div>
 <form onSubmit={submit} className="settingsGrid"><label className="wideField">Discovery brief<textarea rows={3} maxLength={1600} value={query} onChange={e=>setQuery(e.target.value)} disabled={busy}/></label><button disabled={busy||!query.trim()}>{busy?'Researching…':'Discover investors'}</button></form>{error?<p className="muted smallText">{error}</p>:null}
 <div className="settingsList">{candidates.map((c,i)=><div className="settingsRow" key={c.sourceUrl+i}><div><strong>{c.fundName}</strong><span className="smallText">{c.reason}</span><span className="muted smallText">{c.geography??'—'} · {c.stageFit??'stage not sourced'} · <a href={c.sourceUrl} target="_blank" rel="noreferrer">source</a></span>
 <form action={recordFounderInvestorResearchCandidate}><input type="hidden" name="fund_name" value={c.fundName}/><input type="hidden" name="person_name" value=""/><input type="hidden" name="geography" value={c.geography??''}/><input type="hidden" name="stage_fit" value={c.stageFit??''}/><input type="hidden" name="sector_fit" value={c.sectorFit??c.reason}/><input type="hidden" name="ai_saas_fit" value=""/><input type="hidden" name="mena_gcc_fit" value=""/><input type="hidden" name="currency" value=""/><input type="hidden" name="source_url" value={c.sourceUrl}/><input type="hidden" name="source_title" value={c.sourceTitle??''}/><input type="hidden" name="last_verified_date" value={c.verifiedDate}/><input type="hidden" name="notes" value={c.reason}/><button>Save as external research</button></form>
 </div></div>)}</div></section>;
}
