'use server';
import { revalidatePath } from 'next/cache';
import { getCurrentOrganization } from '@/lib/supabase/org';
function req(f:FormData,k:string){const v=String(f.get(k)??'').trim();if(!v)throw new Error(`${k} is required`);return v;}
function opt(f:FormData,k:string){const v=String(f.get(k)??'').trim();return v||null;}
function bound(v:string|null,k:string,m:number){if(v&&v.length>m)throw new Error(`${k} is too long`);return v;}
function uid(v:string,k:string){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v))throw new Error(`${k} is invalid`);return v;}
function date(v:string|null,k:string){if(!v)return null;if(!/^\d{4}-\d{2}-\d{2}$/.test(v))throw new Error(`${k} is invalid`);return v;}
function num(v:string|null,k:string){if(v==null||v==='')return null;const n=Number(v);if(!Number.isFinite(n))throw new Error(`${k} must be numeric`);return n;}
function lines(v:string|null){return (v??'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).slice(0,30);}
async function owner(){const c=await getCurrentOrganization(true);if(!c.userId||c.role!=='OWNER')throw new Error('Owner permission required');return c;}
function ident(f:FormData){const raw=opt(f,'id');if(!raw)return {id:null,version:null};const version=Number(req(f,'version'));if(!Number.isInteger(version)||version<1)throw new Error('Invalid version');return {id:uid(raw,'id'),version};}
async function persist(table:string,c:Awaited<ReturnType<typeof owner>>,id:string|null,version:number|null,payload:Record<string,unknown>){
 if(id&&version){const {data,error}=await c.supabase.from(table).update(payload).eq('organization_id',c.organizationId).eq('id',id).eq('version',version).select('id').maybeSingle();if(error)throw new Error(`${table} update failed: ${error.message}`);if(!data)throw new Error(`${table} version conflict`);}
 else{const {error}=await c.supabase.from(table).insert({organization_id:c.organizationId,...payload,created_by_user_id:c.userId});if(error)throw new Error(`${table} create failed: ${error.message}`);}
 revalidatePath('/founder');
}
export async function saveFounderStrategicGoal(f:FormData){const c=await owner(),{id,version}=ident(f),status=req(f,'status').toUpperCase(),category=req(f,'category').toUpperCase(),horizon=req(f,'horizon').toUpperCase();if(!['DRAFT','ACTIVE','COMPLETED','CANCELED'].includes(status))throw new Error('Invalid goal status');if(!['GROWTH','PRODUCT','REVENUE','CUSTOMER','OPERATIONS','FUNDRAISING','TEAM','OTHER'].includes(category))throw new Error('Invalid goal category');if(!['QUARTER','YEAR','MULTI_YEAR','CUSTOM'].includes(horizon))throw new Error('Invalid goal horizon');await persist('founder_strategic_goals',c,id,version,{status,category,title:req(f,'title').slice(0,240),description:bound(opt(f,'description'),'description',6000),horizon,start_date:date(opt(f,'start_date'),'start_date'),end_date:date(opt(f,'end_date'),'end_date'),source_ref:bound(req(f,'source_ref'),'source_ref',512),evidence:{confirmation:'OWNER_STRATEGIC_INPUT',recordedAt:new Date().toISOString()},notes:bound(opt(f,'notes'),'notes',4000),updated_by_user_id:c.userId});}
export async function saveFounderKeyResult(f:FormData){const c=await owner(),{id,version}=ident(f),status=req(f,'status').toUpperCase(),direction=req(f,'direction').toUpperCase();if(!['NOT_STARTED','ON_TRACK','AT_RISK','ACHIEVED','CANCELED'].includes(status))throw new Error('Invalid key-result status');if(!['INCREASE','DECREASE','MAINTAIN','QUALITATIVE'].includes(direction))throw new Error('Invalid key-result direction');await persist('founder_key_results',c,id,version,{goal_id:uid(req(f,'goal_id'),'goal_id'),status,metric_name:req(f,'metric_name').slice(0,240),unit:bound(opt(f,'unit'),'unit',80),direction,baseline_value:num(opt(f,'baseline_value'),'baseline_value'),target_value:num(opt(f,'target_value'),'target_value'),current_value:num(opt(f,'current_value'),'current_value'),due_date:date(opt(f,'due_date'),'due_date'),source_ref:bound(req(f,'source_ref'),'source_ref',512),evidence:{confirmation:'OWNER_KEY_RESULT_INPUT',recordedAt:new Date().toISOString()},notes:bound(opt(f,'notes'),'notes',4000),updated_by_user_id:c.userId});}
export async function saveFounderMarketResearchItem(f:FormData){const c=await owner(),{id,version}=ident(f),status=req(f,'status').toUpperCase(),research=req(f,'research_type').toUpperCase();if(!['CURRENT','STALE','ARCHIVED'].includes(status))throw new Error('Invalid research status');if(!['MARKET_SIZE','COMPETITOR','PRICING','REGULATION','TREND','INVESTOR','OTHER'].includes(research))throw new Error('Invalid research type');const u=new URL(req(f,'source_url'));if(!['http:','https:'].includes(u.protocol))throw new Error('source_url must be http(s)');const observed=date(req(f,'observed_date'),'observed_date')!,verified=date(req(f,'last_verified_date'),'last_verified_date')!;await persist('founder_market_research_items',c,id,version,{status,research_type:research,title:req(f,'title').slice(0,300),claim:req(f,'claim').slice(0,4000),geography:bound(opt(f,'geography'),'geography',200),segment:bound(opt(f,'segment'),'segment',240),source_url:u.toString(),source_title:bound(opt(f,'source_title'),'source_title',500),observed_at:new Date(`${observed}T12:00:00.000Z`).toISOString(),last_verified_at:new Date(`${verified}T12:00:00.000Z`).toISOString(),notes:bound(opt(f,'notes'),'notes',4000),updated_by_user_id:c.userId});}
export async function saveFounderBoardReport(f:FormData){const c=await owner(),{id,version}=ident(f),status=req(f,'status').toUpperCase();if(!['DRAFT','PUBLISHED','ARCHIVED'].includes(status))throw new Error('Invalid board report status');await persist('founder_board_reports',c,id,version,{status,title:req(f,'title').slice(0,240),period_start:date(req(f,'period_start'),'period_start'),period_end:date(req(f,'period_end'),'period_end'),executive_summary:req(f,'executive_summary').slice(0,12000),decisions_needed:lines(opt(f,'decisions_needed')),risks:lines(opt(f,'risks')),source_ref:bound(req(f,'source_ref'),'source_ref',512),evidence:{confirmation:'OWNER_BOARD_REPORT',recordedAt:new Date().toISOString()},updated_by_user_id:c.userId});}
