import 'server-only';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { FounderBoardReportV1,FounderKeyResultV1,FounderMarketResearchItemV1,FounderStrategicGoalV1,FounderStrategyWorkspaceV1 } from './strategy';

function os(v:unknown){const t=String(v??'').trim();return t||null;}
function on(v:unknown){if(v==null||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null;}
function sl(v:unknown){return Array.isArray(v)?v.filter((x):x is string=>typeof x==='string').map(x=>x.trim()).filter(Boolean).slice(0,30):[];}

export async function loadFounderStrategyWorkspaceV1(input:{supabase:SupabaseClient;organizationId:string;now?:Date}):Promise<FounderStrategyWorkspaceV1>{
 const db=input.supabase,org=input.organizationId,now=input.now??new Date();
 const [a,b,c,d]=await Promise.all([
  db.from('founder_strategic_goals').select('id,status,category,title,description,horizon,start_date,end_date,source_ref,notes,version,updated_at').eq('organization_id',org).order('updated_at',{ascending:false}).limit(200),
  db.from('founder_key_results').select('id,goal_id,status,metric_name,unit,direction,baseline_value,target_value,current_value,due_date,source_ref,notes,version,updated_at').eq('organization_id',org).order('updated_at',{ascending:false}).limit(500),
  db.from('founder_market_research_items').select('id,status,research_type,title,claim,geography,segment,source_url,source_title,observed_at,last_verified_at,notes,version,updated_at').eq('organization_id',org).order('last_verified_at',{ascending:false}).limit(500),
  db.from('founder_board_reports').select('id,status,title,period_start,period_end,executive_summary,decisions_needed,risks,source_ref,version,updated_at').eq('organization_id',org).order('period_end',{ascending:false}).limit(100),
 ]);
 const error=[a.error,b.error,c.error,d.error].find(Boolean);if(error)throw new Error(`Founder strategy workspace read failed: ${error.message}`);
 const goals:FounderStrategicGoalV1[]=(a.data??[]).map(r=>({id:String(r.id),status:r.status==='ACTIVE'?'ACTIVE':r.status==='COMPLETED'?'COMPLETED':r.status==='CANCELED'?'CANCELED':'DRAFT',category:['GROWTH','PRODUCT','REVENUE','CUSTOMER','OPERATIONS','FUNDRAISING','TEAM'].includes(String(r.category))?r.category as FounderStrategicGoalV1['category']:'OTHER',title:String(r.title??''),description:os(r.description),horizon:r.horizon==='YEAR'?'YEAR':r.horizon==='MULTI_YEAR'?'MULTI_YEAR':r.horizon==='CUSTOM'?'CUSTOM':'QUARTER',startDate:os(r.start_date),endDate:os(r.end_date),sourceRef:String(r.source_ref??''),notes:os(r.notes),version:Number(r.version??1),updatedAt:String(r.updated_at??now.toISOString())}));
 const keyResults:FounderKeyResultV1[]=(b.data??[]).map(r=>({id:String(r.id),goalId:String(r.goal_id),status:r.status==='ON_TRACK'?'ON_TRACK':r.status==='AT_RISK'?'AT_RISK':r.status==='ACHIEVED'?'ACHIEVED':r.status==='CANCELED'?'CANCELED':'NOT_STARTED',metricName:String(r.metric_name??''),unit:os(r.unit),direction:r.direction==='DECREASE'?'DECREASE':r.direction==='MAINTAIN'?'MAINTAIN':r.direction==='QUALITATIVE'?'QUALITATIVE':'INCREASE',baselineValue:on(r.baseline_value),targetValue:on(r.target_value),currentValue:on(r.current_value),dueDate:os(r.due_date),sourceRef:String(r.source_ref??''),notes:os(r.notes),version:Number(r.version??1),updatedAt:String(r.updated_at??now.toISOString())}));
 const marketResearch:FounderMarketResearchItemV1[]=(c.data??[]).map(r=>({id:String(r.id),status:r.status==='STALE'?'STALE':r.status==='ARCHIVED'?'ARCHIVED':'CURRENT',researchType:['MARKET_SIZE','COMPETITOR','PRICING','REGULATION','TREND','INVESTOR'].includes(String(r.research_type))?r.research_type as FounderMarketResearchItemV1['researchType']:'OTHER',title:String(r.title??''),claim:String(r.claim??''),geography:os(r.geography),segment:os(r.segment),sourceUrl:String(r.source_url??''),sourceTitle:os(r.source_title),observedAt:String(r.observed_at??now.toISOString()),lastVerifiedAt:String(r.last_verified_at??now.toISOString()),notes:os(r.notes),version:Number(r.version??1),updatedAt:String(r.updated_at??now.toISOString())}));
 const boardReports:FounderBoardReportV1[]=(d.data??[]).map(r=>({id:String(r.id),status:r.status==='PUBLISHED'?'PUBLISHED':r.status==='ARCHIVED'?'ARCHIVED':'DRAFT',title:String(r.title??''),periodStart:String(r.period_start),periodEnd:String(r.period_end),executiveSummary:String(r.executive_summary??''),decisionsNeeded:sl(r.decisions_needed),risks:sl(r.risks),sourceRef:String(r.source_ref??''),version:Number(r.version??1),updatedAt:String(r.updated_at??now.toISOString())}));
 const current=marketResearch.filter(x=>x.status==='CURRENT'),published=boardReports.filter(x=>x.status==='PUBLISHED');
 return {schemaVersion:1,generatedAt:now.toISOString(),goals,keyResults,marketResearch,boardReports,commandCenter:{activeGoals:goals.filter(x=>x.status==='ACTIVE').length,activeKeyResults:keyResults.filter(x=>['NOT_STARTED','ON_TRACK','AT_RISK'].includes(x.status)).length,atRiskKeyResults:keyResults.filter(x=>x.status==='AT_RISK').length,achievedKeyResults:keyResults.filter(x=>x.status==='ACHIEVED').length,currentResearchItems:current.length,currentResearchTypes:[...new Set(current.map(x=>x.researchType))],latestPublishedBoardReportAt:published[0]?.updatedAt??null},evidence:[
  {authority:'STRATEGIC_GOALS',quality:'VERIFIED',evidenceClass:'VERIFIED_PRODUCTION',count:goals.length,detail:'Production strategic-goal authority queried successfully. Goal status is explicit OWNER input.'},
  {authority:'KEY_RESULTS',quality:'VERIFIED',evidenceClass:'VERIFIED_PRODUCTION',count:keyResults.length,detail:'Production key-result authority queried successfully. Current values and status are OWNER-provided evidence.'},
  {authority:'MARKET_RESEARCH',quality:'VERIFIED',evidenceClass:'VERIFIED_PRODUCTION',count:current.length,detail:'Persistent sourced external research queried successfully. Stored claims remain external evidence, not internal performance truth.'},
  {authority:'BOARD_REPORTS',quality:'VERIFIED',evidenceClass:'VERIFIED_PRODUCTION',count:boardReports.length,detail:'Production board-report authority queried successfully. PUBLISHED means OWNER-published, not external board approval.'},
 ]};
}
