import { describe, expect, it } from 'vitest';
import {
  resolveVoiceReplyRuntimeConfig,
  voiceReplySynthesisText,
} from '@/lib/voice/reply-config';

describe('voice reply runtime config', () => {
  it('fails closed when the existing organization config has no explicit voice opt-in', () => {
    expect(resolveVoiceReplyRuntimeConfig({})).toEqual({
      ready: false,
      reason: 'VOICE_REPLY_DISABLED',
    });
  });

  it('requires an explicit AI-generated voice disclosure', () => {
    expect(resolveVoiceReplyRuntimeConfig({
      voiceReply: {
        enabled: true,
        costReserveUsd: 0.01,
        pricingStatus: 'CONSERVATIVE_CONFIGURED_RESERVE',
      },
    })).toEqual({
      ready: false,
      reason: 'AI_VOICE_DISCLOSURE_REQUIRED',
    });
  });

  it('requires a bounded conservative cost reserve instead of pretending exact pricing', () => {
    expect(resolveVoiceReplyRuntimeConfig({
      voiceReply: {
        enabled: true,
        aiGeneratedDisclosureText: 'This voice is generated by AI.',
        costReserveUsd: 0,
        pricingStatus: 'CONSERVATIVE_CONFIGURED_RESERVE',
      },
    })).toEqual({
      ready: false,
      reason: 'VOICE_REPLY_COST_RESERVE_INVALID',
    });

    expect(resolveVoiceReplyRuntimeConfig({
      voiceReply: {
        enabled: true,
        aiGeneratedDisclosureText: 'This voice is generated by AI.',
        costReserveUsd: 0.01,
        pricingStatus: 'FAKE_EXACT_PRICE',
      },
    })).toEqual({
      ready: false,
      reason: 'VOICE_REPLY_PRICING_EVIDENCE_REQUIRED',
    });
  });

  it('accepts only an explicit, conservative and disclosed configuration', () => {
    expect(resolveVoiceReplyRuntimeConfig({
      voiceReply: {
        enabled: true,
        aiGeneratedDisclosureText: '  This voice is generated by AI.  ',
        costReserveUsd: 0.01234567,
        pricingStatus: 'CONSERVATIVE_CONFIGURED_RESERVE',
      },
    })).toEqual({
      ready: true,
      config: {
        enabled: true,
        aiGeneratedDisclosureText: 'This voice is generated by AI.',
        costReserveUsd: 0.012346,
        pricingStatus: 'CONSERVATIVE_CONFIGURED_RESERVE',
      },
    });
  });

  it('prepends disclosure to the exact reply content', () => {
    expect(voiceReplySynthesisText('AI voice disclosure.', 'مرحبا')).toBe(
      'AI voice disclosure.\n\nمرحبا',
    );
  });
});
