import { NextResponse } from 'next/server';

export const runtime='nodejs';

function script(publicKey:string){
  const key=JSON.stringify(publicKey);
  return `(()=>{const s=document.currentScript;if(!s)return;const src=new URL(s.src),base=src.origin,key=${key};if(!/^wc_[A-Za-z0-9_-]{24,80}$/.test(key))return;
const host=document.createElement('div');host.setAttribute('data-smartvisions-webchat','');document.body.appendChild(host);const root=host.attachShadow({mode:'open'});
root.innerHTML='<style>:host{all:initial}.sv-btn{position:fixed;right:20px;bottom:20px;width:56px;height:56px;border:0;border-radius:50%;font:600 22px system-ui;cursor:pointer;box-shadow:0 10px 30px rgba(0,0,0,.2);z-index:2147483000}.sv-panel{position:fixed;right:20px;bottom:88px;width:min(360px,calc(100vw - 24px));height:min(560px,calc(100vh - 120px));background:#fff;border:1px solid #ddd;border-radius:16px;box-shadow:0 16px 50px rgba(0,0,0,.22);display:none;flex-direction:column;overflow:hidden;z-index:2147483000;font:14px system-ui;color:#111}.sv-panel.open{display:flex}.sv-head{padding:10px 12px;border-bottom:1px solid #eee;font-weight:700;display:flex;align-items:center;justify-content:space-between}.sv-close{border:0;background:transparent;font:18px system-ui;cursor:pointer;padding:4px 8px}.sv-body{flex:1;overflow:auto;padding:12px;display:flex;flex-direction:column;gap:8px}.sv-msg{max-width:82%;padding:9px 11px;border-radius:12px;background:#f2f2f2;white-space:pre-wrap;overflow-wrap:anywhere}.sv-msg.out{margin-left:auto;background:#e8eefc}.sv-foot{border-top:1px solid #eee;padding:10px}.sv-file{display:block;width:100%;margin:0 0 8px;font:12px system-ui}.sv-row{display:flex;gap:8px}.sv-input{flex:1;min-width:0;border:1px solid #ccc;border-radius:10px;padding:10px;font:14px system-ui}.sv-send{border:0;border-radius:10px;padding:0 14px;font-weight:600;cursor:pointer}.sv-consent{display:none;padding:12px;border-top:1px solid #eee}.sv-consent.show{display:block}.sv-note{font-size:12px;color:#666;margin-bottom:8px}.sv-error{font-size:12px;color:#a00;margin-top:6px}</style><button class="sv-btn" aria-label="Open chat">✦</button><section class="sv-panel" role="dialog" aria-label="Chat"><div class="sv-head"><span class="sv-title">Chat</span><button class="sv-close" aria-label="End chat">×</button></div><div class="sv-body"></div><div class="sv-consent"><div class="sv-note"></div><label><input type="checkbox" class="sv-check"> I agree</label><div class="sv-error"></div></div><div class="sv-foot"><input class="sv-file" type="file" multiple accept="image/*,video/mp4,video/webm,audio/*,.pdf,.txt,.doc,.docx,.xls,.xlsx"><div class="sv-row"><input class="sv-input" maxlength="4000" placeholder="Type a message"><button class="sv-send">Send</button></div><div class="sv-error"></div></div></section>';
const q=(x)=>root.querySelector(x),btn=q('.sv-btn'),panel=q('.sv-panel'),body=q('.sv-body'),head=q('.sv-title'),close=q('.sv-close'),input=q('.sv-input'),file=q('.sv-file'),send=q('.sv-send'),cons=q('.sv-consent'),check=q('.sv-check'),consNote=cons.querySelector('.sv-note'),errors=root.querySelectorAll('.sv-error');
let cfg=null,state=null,timer=null,last=null,rendered=new Set();const storage='svwc:'+key;
function err(m=''){errors.forEach(e=>e.textContent=m)}function loadState(){try{return JSON.parse(sessionStorage.getItem(storage)||'null')}catch{return null}}function saveState(){try{state?sessionStorage.setItem(storage,JSON.stringify(state)):sessionStorage.removeItem(storage)}catch{}}
async function config(){const r=await fetch(base+'/api/web-chat/config?key='+encodeURIComponent(key),{credentials:'omit',cache:'no-store'});if(!r.ok)throw new Error('Chat is unavailable');cfg=await r.json();head.textContent=cfg.title||'Chat with us';input.maxLength=cfg.maxMessageChars||4000;consNote.textContent=cfg.consentText||'';if(cfg.welcomeMessage){const d=document.createElement('div');d.className='sv-msg';d.textContent=cfg.welcomeMessage;body.appendChild(d)}}
async function session(){if(state?.sessionId&&state?.sessionToken)return state;if(cfg?.consentRequired&&!check.checked){cons.classList.add('show');throw new Error('Please accept the consent notice first.')}const r=await fetch(base+'/api/web-chat/session?key='+encodeURIComponent(key),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({consentAccepted:cfg?.consentRequired?check.checked:true}),credentials:'omit'});if(!r.ok)throw new Error('Unable to start chat');state=await r.json();saveState();cons.classList.remove('show');return state}
function draw(m){if(!m?.id||rendered.has(m.id))return;rendered.add(m.id);const d=document.createElement('div');d.className='sv-msg '+(m.direction==='OUTBOUND'?'':'out');d.textContent=m.text||'';body.appendChild(d);body.scrollTop=body.scrollHeight;last=m.createdAt||last}
async function poll(){if(!state?.sessionId||!state?.sessionToken)return;const u=new URL(base+'/api/web-chat/messages');u.searchParams.set('key',key);if(last)u.searchParams.set('after',last);const r=await fetch(u,{headers:{'X-WebChat-Session-Id':state.sessionId,'X-WebChat-Session-Token':state.sessionToken},credentials:'omit',cache:'no-store'});if(r.status===401){state=null;saveState();return}if(!r.ok)return;const data=await r.json();(data.messages||[]).forEach(draw)}
async function closeNow(){if(timer)clearInterval(timer);if(state?.sessionId&&state?.sessionToken){try{await fetch(base+'/api/web-chat/session?key='+encodeURIComponent(key),{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:state.sessionId,sessionToken:state.sessionToken}),credentials:'omit'})}catch{}}state=null;cfg=null;last=null;rendered=new Set();body.innerHTML='';input.value='';file.value='';saveState();panel.classList.remove('open');}
async function sendNow(){err();const text=input.value.trim(),files=Array.from(file.files||[]);if(!text&&!files.length)return;if(files.length>4){err('You can attach up to 4 files.');return}try{const st=await session();const id=(crypto.randomUUID?crypto.randomUUID():'client_'+Date.now()+'_'+Math.random().toString(36).slice(2));let r;if(files.length){const fd=new FormData();fd.set('sessionId',st.sessionId);fd.set('sessionToken',st.sessionToken);fd.set('clientMessageId',id);fd.set('text',text);files.forEach(v=>fd.append('files',v,v.name));r=await fetch(base+'/api/web-chat/upload?key='+encodeURIComponent(key),{method:'POST',body:fd,credentials:'omit'})}else{r=await fetch(base+'/api/web-chat/message?key='+encodeURIComponent(key),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:st.sessionId,sessionToken:st.sessionToken,clientMessageId:id,text}),credentials:'omit'})}if(!r.ok){const data=await r.json().catch(()=>({}));throw new Error(data.error==='RECONCILIATION_REQUIRED'?'Message accepted upstream; syncing safely. Please do not resend yet.':'Message was not accepted')}input.value='';file.value='';await poll()}catch(e){err(e instanceof Error?e.message:'Chat error')}}
btn.addEventListener('click',async()=>{panel.classList.toggle('open');if(!panel.classList.contains('open')){if(timer)clearInterval(timer);return}try{if(!cfg)await config();state=loadState();if(cfg?.consentRequired&&!state)cons.classList.add('show');await poll();timer=setInterval(poll,2500)}catch(e){err(e instanceof Error?e.message:'Chat unavailable')}});
close.addEventListener('click',closeNow);send.addEventListener('click',sendNow);input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendNow()}});})();`;
}

export async function GET(request:Request){
  const u=new URL(request.url);const key=u.searchParams.get('key')?.trim()??'';
  if(!/^wc_[A-Za-z0-9_-]{24,80}$/.test(key))return new NextResponse('',{status:404});
  return new NextResponse(script(key),{status:200,headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'public, max-age=300','X-Content-Type-Options':'nosniff'}});
}
