'use server';

import { revalidatePath } from 'next/cache';
import { getCurrentOrganization } from '@/lib/supabase/org';

const text=(f:FormData,k:string)=>String(f.get(k)??'').trim();
const required=(f:FormData,k:string)=>{const v=text(f,k);if(!v)throw new Error(`${k} is required`);return v};
const number=(f:FormData,k:string,fallback=0)=>{const raw=text(f,k);if(!raw)return fallback;const v=Number(raw);if(!Number.isFinite(v))throw new Error(`${k} must be numeric`);return v};
const bool=(f:FormData,k:string)=>f.get(k)==='on';
const now=()=>new Date().toISOString();
const integerList=(f:FormData,k:string,min:number,max:number)=>{const raw=text(f,k);if(!raw)return[];const values=raw.split(',').map(v=>Number(v.trim()));if(values.some(v=>!Number.isInteger(v)||v<min||v>max))throw new Error(`${k} contains an invalid value`);return Array.from(new Set(values))};

async function owner(){return getCurrentOrganization(true)}
async function audit(ctx:Awaited<ReturnType<typeof owner>>,action:string,entityType:string,entityId:string|undefined,afterData:unknown){
  const {error}=await ctx.supabase.from('audit_logs').insert({organization_id:ctx.organizationId,actor_type:'USER',actor_id:ctx.userId,action,entity_type:entityType,entity_id:entityId??null,after_data:afterData??null});
  if(error)throw new Error(`Audit log failed: ${error.message}`);
}

export async function updateSystemControls(f:FormData){const ctx=await owner();const payload={global_kill_switch:bool(f,'global_kill_switch'),email_paused:bool(f,'email_paused'),whatsapp_ai_paused:bool(f,'whatsapp_ai_paused'),agents_paused:bool(f,'agents_paused'),shadow_mode:bool(f,'shadow_mode'),updated_at:now()};const{error}=await ctx.supabase.from('system_controls').upsert({organization_id:ctx.organizationId,...payload},{onConflict:'organization_id'});if(error)throw error;await audit(ctx,'UPDATE_RUNTIME_CONTROLS','system_controls',ctx.organizationId,payload);revalidatePath('/system');revalidatePath('/')}

export async function createCampaign(f:FormData){const ctx=await owner();const payload={organization_id:ctx.organizationId,name:required(f,'name'),hunter_type:required(f,'hunter_type'),country_code:text(f,'country_code').toUpperCase()||null,city:text(f,'city')||null,industry:text(f,'industry')||null,target_count:Math.max(1,Math.round(number(f,'target_count',25))),status:'DRAFT',config:{}};const{data,error}=await ctx.supabase.from('campaigns').insert(payload).select('id').single();if(error)throw error;await audit(ctx,'CREATE_CAMPAIGN','campaign',data.id,payload);revalidatePath('/campaigns');revalidatePath('/hunters')}

export async function updateCampaign(f:FormData){const ctx=await owner();const id=required(f,'id');const allowed=['DRAFT','RUNNING','PAUSED','COMPLETED','FAILED'];const status=required(f,'status').toUpperCase();if(!allowed.includes(status))throw new Error('invalid campaign status');const payload={status,target_count:Math.max(1,Math.round(number(f,'target_count',25))),updated_at:now()};const{error}=await ctx.supabase.from('campaigns').update(payload).eq('organization_id',ctx.organizationId).eq('id',id);if(error)throw error;await audit(ctx,'UPDATE_CAMPAIGN','campaign',id,payload);revalidatePath('/campaigns');revalidatePath('/hunters')}

export async function updateOutreachPolicy(f:FormData){const ctx=await owner();const id=required(f,'id');const business_days=integerList(f,'business_days',0,6);const followup_delays_days=integerList(f,'followup_delays_days',1,90);const max_followups=Math.max(0,Math.round(number(f,'max_followups')));if(business_days.length===0)throw new Error('At least one business day is required');if(followup_delays_days.length<max_followups)throw new Error('Follow-up delays must cover every configured follow-up');const payload={enabled:bool(f,'enabled'),send_window_start:required(f,'send_window_start'),send_window_end:required(f,'send_window_end'),business_days,max_emails_per_day:Math.max(0,Math.round(number(f,'max_emails_per_day'))),max_emails_per_mailbox:Math.max(0,Math.round(number(f,'max_emails_per_mailbox'))),max_followups,followup_delays_days,manual_review_required:bool(f,'manual_review_required'),updated_at:now()};const{error}=await ctx.supabase.from('outreach_policies').update(payload).eq('organization_id',ctx.organizationId).eq('id',id);if(error)throw error;await audit(ctx,'UPDATE_OUTREACH_POLICY','outreach_policy',id,payload);revalidatePath('/outreach')}

export async function createMessageTemplate(f:FormData){const ctx=await owner();const payload={organization_id:ctx.organizationId,name:required(f,'name'),channel:required(f,'channel').toUpperCase(),purpose:required(f,'purpose').toUpperCase(),country_code:text(f,'country_code').toUpperCase()||null,language:required(f,'language'),subject:text(f,'subject')||null,body:required(f,'body'),enabled:true,is_default:bool(f,'is_default'),config:{}};const{data,error}=await ctx.supabase.from('message_templates').insert(payload).select('id').single();if(error)throw error;await audit(ctx,'CREATE_MESSAGE_TEMPLATE','message_template',data.id,{...payload,body:'[stored]'});revalidatePath('/messages')}

export async function updateMessageTemplate(f:FormData){const ctx=await owner();const id=required(f,'id');const payload={name:required(f,'name'),subject:text(f,'subject')||null,body:required(f,'body'),enabled:bool(f,'enabled'),is_default:bool(f,'is_default'),updated_at:now()};const{error}=await ctx.supabase.from('message_templates').update(payload).eq('organization_id',ctx.organizationId).eq('id',id);if(error)throw error;await audit(ctx,'UPDATE_MESSAGE_TEMPLATE','message_template',id,{...payload,body:'[stored]'});revalidatePath('/messages')}

export async function createAutomationRule(f:FormData){const ctx=await owner();const payload={organization_id:ctx.organizationId,name:required(f,'name'),trigger_key:required(f,'trigger_key'),action_key:required(f,'action_key'),enabled:true,priority:Math.min(100,Math.max(0,Math.round(number(f,'priority',50)))),config:{}};const{data,error}=await ctx.supabase.from('automation_rules').insert(payload).select('id').single();if(error)throw error;await audit(ctx,'CREATE_AUTOMATION_RULE','automation_rule',data.id,payload);revalidatePath('/automations')}

export async function updateAutomationRule(f:FormData){const ctx=await owner();const id=required(f,'id');const payload={enabled:bool(f,'enabled'),priority:Math.min(100,Math.max(0,Math.round(number(f,'priority',50)))),updated_at:now()};const{error}=await ctx.supabase.from('automation_rules').update(payload).eq('organization_id',ctx.organizationId).eq('id',id);if(error)throw error;await audit(ctx,'UPDATE_AUTOMATION_RULE','automation_rule',id,payload);revalidatePath('/automations')}

export async function updateIntegration(f:FormData){const ctx=await owner();const id=required(f,'id');const payload={enabled:bool(f,'enabled'),account_label:text(f,'account_label')||null,updated_at:now()};const{error}=await ctx.supabase.from('integration_connections').update(payload).eq('organization_id',ctx.organizationId).eq('id',id);if(error)throw error;await audit(ctx,'UPDATE_INTEGRATION','integration',id,payload);revalidatePath('/integrations')}

export async function updateOrganizationSettings(f:FormData){const ctx=await owner();const payload={organization_id:ctx.organizationId,brand_name:required(f,'brand_name'),operator_language:required(f,'operator_language'),default_customer_language:required(f,'default_customer_language'),notification_email:text(f,'notification_email')||null,updated_at:now()};const{error}=await ctx.supabase.from('organization_settings').upsert(payload,{onConflict:'organization_id'});if(error)throw error;await audit(ctx,'UPDATE_ORGANIZATION_SETTINGS','organization_settings',ctx.organizationId,payload);revalidatePath('/settings')}

export async function createKnowledge(f:FormData){const ctx=await owner();const key=required(f,'knowledge_key');const content=required(f,'content');const{data,error}=await ctx.supabase.rpc('publish_knowledge_version',{p_organization_id:ctx.organizationId,p_knowledge_key:key,p_payload:{text:content}});if(error)throw error;const published=Array.isArray(data)?data[0]:data;if(!published?.id||!published?.version)throw new Error('Knowledge publisher returned no version');revalidatePath('/knowledge')}

export async function createPromptVersion(f:FormData){const ctx=await owner();const agent=required(f,'agent_name');const promptText=required(f,'prompt_text');const{data,error}=await ctx.supabase.rpc('publish_prompt_version',{p_organization_id:ctx.organizationId,p_agent_name:agent,p_prompt_text:promptText});if(error)throw error;const published=Array.isArray(data)?data[0]:data;if(!published?.id||!published?.version)throw new Error('Prompt publisher returned no version');revalidatePath('/agents')}

export async function updateLead(f:FormData){const ctx=await owner();const id=required(f,'id');const statuses=['NEW','AUDITED','QUALIFIED','READY_TO_CONTACT','CONTACTED','REPLIED','INTERESTED','HOT','HUMAN','WON','LOST','DO_NOT_CONTACT'];const modes=['AUTO','PAUSED','HUMAN'];const status=required(f,'status');const agent_mode=required(f,'agent_mode');if(!statuses.includes(status)||!modes.includes(agent_mode))throw new Error('invalid lead state');const payload={status,agent_mode,recommended_offer:text(f,'recommended_offer')||null,updated_at:now()};const{error}=await ctx.supabase.from('leads').update(payload).eq('organization_id',ctx.organizationId).eq('id',id);if(error)throw error;await audit(ctx,'UPDATE_LEAD','lead',id,payload);revalidatePath('/leads');revalidatePath('/hot-leads')}

export async function addSuppression(f:FormData){const ctx=await owner();const email=text(f,'email')||null,phone=text(f,'phone')||null,domain=text(f,'domain')||null;if(!email&&!phone&&!domain)throw new Error('email, phone or domain required');const payload={organization_id:ctx.organizationId,email,phone,domain,reason:text(f,'reason')||'MANUAL',source:'CONTROL_CENTER'};const{data,error}=await ctx.supabase.from('suppression_list').insert(payload).select('id').single();if(error)throw error;await audit(ctx,'ADD_SUPPRESSION','suppression',data.id,payload);revalidatePath('/suppression')}

export async function updatePortfolioItem(f:FormData){const ctx=await owner();const id=required(f,'id');const payload={title:required(f,'title'),summary:text(f,'summary')||null,public_url:text(f,'public_url')||null,approved:bool(f,'approved'),updated_at:now()};const{error}=await ctx.supabase.from('portfolio_items').update(payload).eq('organization_id',ctx.organizationId).eq('id',id);if(error)throw error;await audit(ctx,'UPDATE_PORTFOLIO_ITEM','portfolio_item',id,payload);revalidatePath('/portfolio')}

export async function updatePreviewTemplate(f:FormData){const ctx=await owner();const id=required(f,'id');const payload={name:required(f,'name'),active:bool(f,'active'),quality_tier:required(f,'quality_tier'),updated_at:now()};const{error}=await ctx.supabase.from('preview_templates').update(payload).eq('organization_id',ctx.organizationId).eq('id',id);if(error)throw error;await audit(ctx,'UPDATE_PREVIEW_TEMPLATE','preview_template',id,payload);revalidatePath('/preview-studio')}

export async function approveMessage(f:FormData){const ctx=await owner();const id=required(f,'id');const payload={requires_approval:false,status:'APPROVED',approval_reason:null,processed_at:now()};const{error}=await ctx.supabase.from('conversation_messages').update(payload).eq('organization_id',ctx.organizationId).eq('id',id);if(error)throw error;await audit(ctx,'APPROVE_MESSAGE','conversation_message',id,payload);revalidatePath('/approvals');revalidatePath('/conversations')}

export async function rejectMessage(f:FormData){const ctx=await owner();const id=required(f,'id');const payload={requires_approval:false,status:'BLOCKED',approval_reason:text(f,'reason')||'Rejected by owner',processed_at:now()};const{error}=await ctx.supabase.from('conversation_messages').update(payload).eq('organization_id',ctx.organizationId).eq('id',id);if(error)throw error;await audit(ctx,'REJECT_MESSAGE','conversation_message',id,payload);revalidatePath('/approvals');revalidatePath('/conversations')}

export async function updateConversation(f:FormData){const ctx=await owner();const id=required(f,'id');const stages=['NEW','ACTIVE','CLOSING','WAITING_CUSTOMER','UNANSWERED','HOT','NEEDS_HUMAN','FOLLOW_UP_DUE','WON','LOST','DO_NOT_CONTACT','SPAM','PAUSED'];const stage=required(f,'stage');if(!stages.includes(stage))throw new Error('invalid conversation stage');const requires_human=bool(f,'requires_human');const payload={stage,requires_human,awaiting_party:requires_human?'HUMAN':stage==='WAITING_CUSTOMER'?'CUSTOMER':'NONE',priority:Math.min(100,Math.max(0,Math.round(number(f,'priority',50)))),updated_at:now()};const{error}=await ctx.supabase.from('sales_conversations').update(payload).eq('organization_id',ctx.organizationId).eq('id',id);if(error)throw error;await audit(ctx,'UPDATE_CONVERSATION','sales_conversation',id,payload);revalidatePath('/conversations');revalidatePath(`/conversations/${id}`)}