import { createMessageTemplate, updateMessageTemplate } from '@/app/management-actions';
import { getCurrentOrganization } from '@/lib/supabase/org';
export const dynamic = 'force-dynamic';

export default async function MessageStudioPage(){
  const {supabase,organizationId,role}=await getCurrentOrganization();
  const {data}=await supabase.from('message_templates').select('*').eq('organization_id',organizationId).order('updated_at',{ascending:false}); const rows=data??[]; const editable=role==='OWNER';
  return <div><div className="headerRow"><div><h1>Message Studio</h1><p className="muted">Customer-facing templates by channel, market and purpose. Persian operator previews remain generated separately.</p></div><span className="status">{rows.filter(r=>r.enabled).length} enabled</span></div>
  <div className="settingsList">{rows.map(r=><form action={updateMessageTemplate} className="settingsRow templateRow" key={r.id}><input type="hidden" name="id" value={r.id}/><div><strong>{r.name}</strong><span className="muted smallText">{r.channel} · {r.purpose} · {r.country_code||'GLOBAL'} · {r.language}</span></div><label>Name<input name="name" defaultValue={r.name} disabled={!editable}/></label><label>Subject<input name="subject" defaultValue={r.subject??''} disabled={!editable}/></label><label className="wideField">Body<textarea name="body" defaultValue={r.body} rows={4} disabled={!editable}/></label><label className="toggleLabel"><input type="checkbox" name="enabled" defaultChecked={r.enabled} disabled={!editable}/> Enabled</label><label className="toggleLabel"><input type="checkbox" name="is_default" defaultChecked={r.is_default} disabled={!editable}/> Default</label><button disabled={!editable}>Save</button></form>)}</div>
  {editable?<section className="panel settingsCreate"><h2>Create template</h2><form action={createMessageTemplate} className="settingsGrid"><label>Name<input name="name" required/></label><label>Channel<select name="channel"><option>EMAIL</option><option>WHATSAPP</option><option>INSTAGRAM</option><option>OTHER</option></select></label><label>Purpose<select name="purpose"><option>FIRST_TOUCH</option><option>FOLLOW_UP</option><option>REPLY</option><option>HOT_LEAD</option><option>REACTIVATION</option></select></label><label>Country<input name="country_code" placeholder="OM or blank"/></label><label>Language<input name="language" defaultValue="en"/></label><label>Subject<input name="subject"/></label><label className="wideField">Body<textarea name="body" rows={5} required/></label><label className="toggleLabel"><input type="checkbox" name="is_default"/> Default</label><button>Create</button></form></section>:null}</div>;
}
