import type { SupabaseClient } from '@supabase/supabase-js';import { ensureChatwootPublicConversationProjection } from '@/lib/chatwoot/public-conversation-projection';import type { MetaMessengerRoute } from './tenant-routing';import type { NormalizedMessengerEvent } from './webhook';
export type MessengerBusinessResolution={status:'NO_MATCH'}|{status:'MATCH';businessId:string;identityId:string};
export async function resolveMessengerInboundBusiness(input:{service:SupabaseClient;route:MetaMessengerRoute;event:NormalizedMessengerEvent}):Promise<MessengerBusinessResolution>{if(!input.event.senderId)return{status:'NO_MATCH'};const {data,error}=await input.service.rpc('resolve_facebook_messenger_provider_business',{p_organization_id:input.route.organizationId,p_binding_id:input.route.bindingId,p_provider_user_id:input.event.senderId});if(error)throw new Error(`Messenger canonical identity resolution failed: ${error.message}`);if(!Array.isArray(data)||data.length===0)return{status:'NO_MATCH'};if(data.length!==1)throw new Error('Messenger canonical identity resolution was not unique');return{status:'MATCH',businessId:String(data[0].business_id),identityId:String(data[0].identity_id)}}

function text(v:unknown){return typeof v==='string'&&v.trim()?v.trim():null}
function media(event:NormalizedMessengerEvent){const a=Array.isArray(event.payload.attachments)?event.payload.attachments:[];const first=a[0];const t=first&&typeof first==='object'&&!Array.isArray(first)?String((first as Record<string,unknown>).type??'').toLowerCase():'';if(t==='image')return'IMAGE';if(t==='video')return'VIDEO';if(t==='audio')return'AUDIO';if(t==='file')return'DOCUMENT';return a.length?'OTHER':'TEXT'}
export async function projectMatchedMessengerInbound(input:{service:SupabaseClient;route:MetaMessengerRoute;event:NormalizedMessengerEvent;identity:Extract<MessengerBusinessResolution,{status:'MATCH'}>}){
 if(input.event.eventType!=='MESSAGE'||input.event.payload.isEcho===true)return{projected:false as const,reason:'NOT_CUSTOMER_MESSAGE' as const};
 const providerMessageId=text(input.event.payload.messageId);if(!providerMessageId)throw new Error('Messenger inbound message is missing provider message id');
 const external=await ensureChatwootPublicConversationProjection({service:input.service,organizationId:input.route.organizationId,tenantBusinessId:input.route.tenantBusinessId,bindingId:input.route.bindingId,canonicalIdentityId:input.identity.identityId});
 const displayId=Number(external.conversation.id),contactId=Number(external.contact.id);if(!Number.isInteger(displayId)||displayId<=0||!Number.isSafeInteger(contactId)||contactId<=0)throw new Error('Chatwoot projection returned invalid canonical identifiers');
 const {data,error}=await input.service.rpc('project_facebook_messenger_inbound_message',{p_organization_id:input.route.organizationId,p_tenant_business_id:input.route.tenantBusinessId,p_branch_id:input.route.branchId,p_binding_id:input.route.bindingId,p_business_id:input.identity.businessId,p_identity_id:input.identity.identityId,p_provider_message_id:providerMessageId,p_message_text:text(input.event.payload.text),p_media_type:media(input.event),p_chatwoot_conversation_display_id:displayId,p_chatwoot_conversation_uuid:text(external.conversation.uuid),p_chatwoot_contact_id:contactId,p_occurred_at:input.event.occurredAt??null,p_request_key:`messenger:${providerMessageId}`.slice(0,200)});
 if(error)throw new Error(`Messenger inbound CRM projection failed: ${error.message}`);const row=Array.isArray(data)?data[0]:data;if(!row?.conversation_id||!row?.message_id||!row?.projection_id)throw new Error('Messenger inbound CRM projection returned invalid result');
 return{projected:true as const,leadId:String(row.lead_id),conversationId:String(row.conversation_id),messageId:String(row.message_id),projectionId:String(row.projection_id),messageInserted:Boolean(row.message_inserted),chatwootOutcome:external.outcome};
}
