import Link from 'next/link';
import { notFound } from 'next/navigation';
import { runDeterministicWebsiteAudit } from '@/app/audit-actions';
import { refreshGoogleBusinessIntelligence } from '@/app/intelligence-actions';
import { getCurrentOrganization } from '@/lib/supabase/org';
import { recordWhatsAppMarketingOptIn, recordWhatsAppMarketingOptOut } from '@/app/whatsapp-opt-in-actions';
import { evaluateWhatsAppMarketingPermission, normalizeWhatsAppRecipient, WHATSAPP_OPT_IN_SOURCE_TYPES } from '@/lib/whatsapp/marketing-opt-in';

export const dynamic='force-dynamic';
const formatMuscat=(value:string|null|undefined)=>value?new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Muscat',dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—';
type Props={params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>};
type Review={rating?:number;text?:string;relativePublishTimeDescription?:string;publishTime?:string;authorName?:string;authorUri?:string};

export default async function LeadDetailPage({params,searchParams}:Props){
 const{id}=await params;const query=await searchParams;const{supabase,organizationId,role}=await getCurrentOrganization();
 const{data:lead}=await supabase.from('leads').select('id,status,opportunity_score,intent_score,agent_mode,business_id,score_reasons,businesses(id,name,country_code,city,category,google_place_id,official_website,email,phone,whatsapp,instagram,formatted_address,google_maps_uri,international_phone,google_rating,google_user_rating_count,google_business_status,google_price_level,google_primary_type_display_name,google_opening_hours,google_reviews,google_review_summary,google_intelligence_retrieved_at)').eq('organization_id',organizationId).eq('id',id).maybeSingle();
 if(!lead)notFound();const business=Array.isArray(lead.businesses)?lead.businesses[0]:lead.businesses;
 const{data:audits}=business?.id?await supabase.from('website_audits').select('id,status,source_url,title,detected_languages,has_arabic,has_english,has_booking,has_whatsapp,mobile_quality,seo_quality,cta_quality,contact_emails,contact_phones,social_links,evidence,error_message,audited_at,created_at').eq('organization_id',organizationId).eq('business_id',business.id).order('created_at',{ascending:false}).limit(10):{data:[]};
 const whatsappRecipient=normalizeWhatsAppRecipient(business?.whatsapp||business?.international_phone||business?.phone);
 const{data:permissionRows}=await supabase.from('lead_sources').select('field_name,value,source_type,source_url,retrieved_at,verified_at').eq('organization_id',organizationId).eq('lead_id',lead.id).in('field_name',['whatsapp_marketing_opt_in','whatsapp_marketing_opt_out']).order('retrieved_at',{ascending:false}).limit(20);
 const whatsappPermission=evaluateWhatsAppMarketingPermission(permissionRows??[],whatsappRecipient);
 const latest=audits?.[0];const latestSuccessful=audits?.find((a)=>a.status==='SUCCEEDED');const reviews=(Array.isArray(business?.google_reviews)?business.google_reviews:[]) as Review[];const hours=(business?.google_opening_hours&&typeof business.google_opening_hours==='object'?business.google_opening_hours:{}) as {openNow?:boolean;weekdayDescriptions?:string[]};
 const auditMessage=query.audit==='success'?'Website audit succeeded. No LLM or paid audit provider was used.':query.audit==='cached'?'Fresh cached audit reused; no website request was made.':query.audit==='error'?`Audit failed: ${String(query.message??'unknown error')}`:null;
 const intelMessage=query.intel==='success'?'Google Business intelligence refreshed and cached.':query.intel==='cached'?'Fresh Google intelligence cache reused; no Google request was made.':null;
 const priority=String(business?.google_business_status??'').toUpperCase()==='OPERATIONAL'&&!String(business?.official_website??'').trim();
 const displayAudit=latestSuccessful??latest;
 return <div>
  <div className="headerRow"><div><h1>{business?.name??'Lead'}</h1><p className="muted">Google business intelligence + controlled evidence. Oman time. Outreach remains disabled.</p></div><Link className="textLink" href="/leads">← Leads</Link></div>
  {auditMessage?<section className="panel"><strong>{auditMessage}</strong></section>:null}{intelMessage?<section className="panel"><strong>{intelMessage}</strong></section>:null}
  {priority?<section className="panel"><strong>PRIORITY LEAD: Google marks this business operational and no official website is present.</strong><p className="muted">This is the primary website-sales target class. Website audit is not applicable until a website exists.</p></section>:null}
  <section className="statsGrid fourStats"><article><span>Status</span><strong>{lead.status}</strong></article><article><span>Opportunity</span><strong>{lead.opportunity_score}/100</strong></article><article><span>Google rating</span><strong>{business?.google_rating??'—'} / 5</strong></article><article><span>Outreach</span><strong>DISABLED</strong></article></section>
  <section className="panel"><h2>Qualification</h2><div className="healthList"><span>Business status <strong>{business?.google_business_status??'—'}</strong></span><span>Official website <strong>{business?.official_website?'PRESENT':'NOT FOUND'}</strong></span><span>Total Google ratings <strong>{business?.google_user_rating_count??'—'}</strong></span><span>Cached review subset <strong>{reviews.length}</strong></span></div>{Array.isArray(lead.score_reasons)&&lead.score_reasons.length?<div><h3>Score reasons</h3>{lead.score_reasons.map((x:string)=><p className="muted" key={x}>• {x}</p>)}</div>:null}</section>
  <section className="panel"><h2>Google Business Profile</h2><p className="muted">Owner-triggered refresh only. Results are cached for 30 days so normal page loads and repeat clicks do not create another paid Google request.</p><div className="healthList"><span>Category <strong>{business?.google_primary_type_display_name??business?.category??'—'}</strong></span><span>Status <strong>{business?.google_business_status??'—'}</strong></span><span>Address <strong>{business?.formatted_address??'—'}</strong></span><span>Phone <strong>{business?.phone??'—'}</strong></span><span>International phone <strong>{business?.international_phone??'—'}</strong></span><span>Website <strong>{business?.official_website??'NOT FOUND'}</strong></span><span>Price level <strong>{business?.google_price_level??'—'}</strong></span><span>Open now <strong>{hours.openNow===true?'YES':hours.openNow===false?'NO':'—'}</strong></span><span>Google data cached <strong>{formatMuscat(business?.google_intelligence_retrieved_at)} Oman time</strong></span></div><form action={refreshGoogleBusinessIntelligence}><input type="hidden" name="leadId" value={lead.id}/><button disabled={role!=='OWNER'||!business?.google_place_id}>{business?.google_intelligence_retrieved_at?'Use cached / refresh after expiry':'Fetch Google rating, reviews & details'}</button></form>{business?.google_maps_uri?<p><a className="textLink" href={business.google_maps_uri} target="_blank" rel="noreferrer">Open Google Maps ↗</a></p>:null}{hours.weekdayDescriptions?.length?<div><h3>Opening hours</h3>{hours.weekdayDescriptions.map((x:string)=><p key={x} className="muted">{x}</p>)}</div>:null}</section>
  <section className="panel"><h2>Google Reviews</h2><p className="muted">Showing {reviews.length} cached review entries out of {business?.google_user_rating_count??'—'} total Google ratings. Places API returns only a subset, not the full review corpus.</p>{business?.google_review_summary?<p><strong>Google review summary:</strong> {business.google_review_summary}</p>:null}{reviews.length?reviews.map((r,i)=><article key={`${r.authorName??'review'}-${i}`} style={{marginBottom:18}}><strong>{r.authorName??'Google user'} · {r.rating??'—'}/5</strong><p>{r.text??'No review text returned.'}</p><small className="muted">{r.relativePublishTimeDescription??(r.publishTime?formatMuscat(r.publishTime):'')}</small></article>):<p className="muted">No review entries are cached yet.</p>}</section>
  <section className="panel"><h2>WhatsApp marketing permission</h2><div className="healthList"><span>Canonical recipient <strong>{whatsappRecipient||'NOT AVAILABLE'}</strong></span><span>Status <strong>{whatsappPermission.allowed?'VERIFIED OPT-IN':whatsappPermission.reason}</strong></span>{whatsappPermission.allowed?<span>Verified <strong>{formatMuscat(whatsappPermission.verifiedAt)} Oman time</strong></span>:null}</div><p className="muted">A public WhatsApp number is not permission. Recording opt-in immediately queues the approved Smart Visions Oman introduction template in Shadow Approval; Meta is not contacted until the owner approves and explicitly sends it.</p>{role==='OWNER'&&whatsappRecipient&&!whatsappPermission.allowed?<form action={recordWhatsAppMarketingOptIn}><input type="hidden" name="leadId" value={lead.id}/><input type="hidden" name="occurredAt" value={new Date().toISOString()}/><label>Permission source<select name="sourceType" defaultValue={WHATSAPP_OPT_IN_SOURCE_TYPES[0]}>{WHATSAPP_OPT_IN_SOURCE_TYPES.map(source=><option key={source} value={source}>{source.replaceAll('_',' ')}</option>)}</select></label><label>Evidence reference<input name="sourceReference" required maxLength={500} placeholder="WhatsApp message ID, form submission ID, or signed/verbal record reference"/></label><label className="toggleLabel"><input type="checkbox" name="attestation" required/> I confirm this customer explicitly agreed to receive Smart Visions marketing messages on WhatsApp.</label><button>Record opt-in and queue intro</button></form>:null}{role==='OWNER'&&whatsappRecipient&&whatsappPermission.allowed?<form action={recordWhatsAppMarketingOptOut}><input type="hidden" name="leadId" value={lead.id}/><button className="rejectButton">Record WhatsApp opt-out</button></form>:null}</section>
  <section className="panel"><h2>Website audit</h2>{business?.official_website?<><p className="muted">SSRF-protected deterministic audit with timeout, body cap, daily quota and cache. No LLM and no outreach.</p><form action={runDeterministicWebsiteAudit}><input type="hidden" name="leadId" value={lead.id}/><button disabled={role!=='OWNER'}>Run deterministic audit</button></form></>:<p className="muted"><strong>NOT APPLICABLE:</strong> no official website is present. This is exactly why the business is a priority sales lead.</p>}</section>
  <section className="panel"><h2>Website audit evidence</h2>{!displayAudit?<p className="muted">No audit has been run yet.</p>:<div className="healthList"><span>Displayed result <strong>{displayAudit.status}</strong></span><span>Title <strong>{displayAudit.title??'—'}</strong></span><span>Languages <strong>{(displayAudit.detected_languages??[]).join(', ')||'—'}</strong></span><span>Mobile <strong>{displayAudit.mobile_quality??'—'}</strong></span><span>SEO <strong>{displayAudit.seo_quality??'—'}</strong></span><span>CTA <strong>{displayAudit.cta_quality??'—'}</strong></span><span>Booking <strong>{displayAudit.has_booking===true?'YES':displayAudit.has_booking===false?'NO':'—'}</strong></span><span>WhatsApp <strong>{displayAudit.has_whatsapp===true?'YES':displayAudit.has_whatsapp===false?'NO':'—'}</strong></span><span>Arabic <strong>{displayAudit.has_arabic===true?'YES':displayAudit.has_arabic===false?'NO':'—'}</strong></span><span>English <strong>{displayAudit.has_english===true?'YES':displayAudit.has_english===false?'NO':'—'}</strong></span><span>Audited <strong>{formatMuscat(displayAudit.audited_at)} Oman time</strong></span>{displayAudit.error_message?<span>Error <strong>{displayAudit.error_message}</strong></span>:null}{latestSuccessful&&latest?.status==='FAILED'?<span>History <strong>Older failed attempt retained; latest successful evidence shown.</strong></span>:null}</div>}</section>
 </div>;
}
