import { createCampaign, updateCampaign } from '@/app/management-actions';
import { getCurrentOrganization } from '@/lib/supabase/org';
import { effectiveCampaignStatus } from '@/lib/reliability/operational-truth';
export const dynamic='force-dynamic';

export default async function CampaignsPage(){
  const {supabase,organizationId,role}=await getCurrentOrganization();
  const {data}=await supabase.from('campaigns').select('*').eq('organization_id',organizationId).order('updated_at',{ascending:false});
  const rows=data??[];
  const effective=rows.map(row=>({row,state:effectiveCampaignStatus(row)}));
  const editable=role==='OWNER';
  return <div><div className="headerRow"><div><h1>Campaigns</h1><p className="muted">Build and control discovery/outreach campaigns by market, city, industry and target volume. Operational state reflects terminal caps even if a legacy row still carries RUNNING.</p></div><span className="status">{effective.filter(x=>x.state.status==='RUNNING').length} running</span></div><section className="grid"><div className="card"><span className="muted">Draft</span><div className="value">{effective.filter(x=>x.state.status==='DRAFT').length}</div></div><div className="card"><span className="muted">Running</span><div className="value">{effective.filter(x=>x.state.status==='RUNNING').length}</div></div><div className="card"><span className="muted">Paused</span><div className="value">{effective.filter(x=>x.state.status==='PAUSED').length}</div></div><div className="card"><span className="muted">Completed</span><div className="value">{effective.filter(x=>x.state.status==='COMPLETED').length}</div></div></section><div className="settingsList">{effective.map(({row:r,state})=><form action={updateCampaign} className="settingsRow campaignRow" key={r.id}><input type="hidden" name="id" value={r.id}/><div><strong>{r.name}</strong><span className="muted smallText">{r.hunter_type} · {[r.country_code,r.city,r.industry].filter(Boolean).join(' · ')||'Global'}</span>{state.reason?<span className="muted smallText">Effective state: {state.status} · {state.reason}</span>:null}</div><label>Status<select name="status" defaultValue={state.status} disabled={!editable}><option>DRAFT</option><option>RUNNING</option><option>PAUSED</option><option>COMPLETED</option><option>FAILED</option></select></label><label>Target count<input type="number" min="1" name="target_count" defaultValue={r.target_count} disabled={!editable}/></label><button disabled={!editable}>Save</button></form>)}</div>{editable?<section className="panel settingsCreate"><h2>Create campaign</h2><form action={createCampaign} className="settingsGrid"><label>Name<input name="name" required placeholder="Muscat dental clinics"/></label><label>Hunter<select name="hunter_type"><option value="BUSINESS">Business Hunter</option><option value="INTENT">Project / Intent Hunter</option></select></label><label>Country<input name="country_code" placeholder="OM" maxLength={2}/></label><label>City<input name="city" placeholder="Muscat"/></label><label>Industry<input name="industry" placeholder="Dental clinic"/></label><label>Target leads<input type="number" min="1" name="target_count" defaultValue="25"/></label><button>Create draft</button></form></section>:null}</div>
}
